export const AUDIT_ACTIONS = [
	"PROJECT_CREATED",
	"PROJECT_UPDATED",
	"PROJECT_DELETED",
	"PROJECT_OWNERSHIP_TRANSFERRED",
	"MEMBER_INVITED",
	"MEMBER_INVITE_ACCEPTED",
	"MEMBER_ROLE_UPDATED",
	"MEMBER_REMOVED",
	"MEMBER_LEFT",
	"DOCUMENT_UPDATED",
	"DOCUMENT_DELETED",
	"CODE_CREATED",
	"CODE_UPDATED",
	"CODE_DELETED",
	"QUOTE_CREATED",
	"QUOTE_COLOR_UPDATED",
	"QUOTE_DELETED",
	"QUOTE_CODE_ASSIGNED",
	"QUOTE_CODE_REMOVED",
	"MEMO_CREATED",
	"MEMO_UPDATED",
	"MEMO_DELETED",
	"DOCUMENT_UPLOADED",
	"DOCUMENT_PDF_ATTACHED",
	"BIBTEX_IMPORTED",
	"DOCUMENT_ENRICHMENT_SCHEDULED",
	"CODE_COMMENT_ADDED",
	"CODE_COMMENT_DELETED",
	"QUOTE_COMMENT_ADDED",
	"QUOTE_COMMENT_DELETED",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];

export const AUDIT_ENTITY_TYPES = [
	"PROJECT",
	"PROJECT_MEMBER",
	"DOCUMENT",
	"CODE",
	"QUOTE",
	"QUOTE_CODE",
	"MEMO",
] as const;

export type AuditEntityType = (typeof AUDIT_ENTITY_TYPES)[number];
